apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1mjv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-1mjv@sha256:0809c5e4ebfd6b8d0b4796905639c7aa0d737d51a03cac54cb5a0b1b705efcae
        name: my-nodejs
        resources: {}
status: {}
